### ISSUE TITLE
Display Flicker

### ISSUE THREAD

**Issue by b-forsberg** [rbwhipple/VRA-FS#2]
First of all nice job with this project. I just finished putting mine together and am currently testing. The text portions at the top and bottom of the display are flickering with the bottom of the display the worse. I just want to ask if this is expected behavior or do I have a problem? I assume this is just the display being redrawn. Thanks for your time.

**Comment by rbwhipple** [comment]
Yes, the behavior is normal.  I erase and redisplay everything each scan. I suppose a clever programmer could handle it better, but it is what it is.  Dick

 

Dick  Whipple

 ***@***.***> ***@***.***

(830) 275-3456

 

From: b-forsberg ***@***.***> 
Sent: Saturday, July 23, 2022 9:32 PM
To: rbwhipple/VRA-FS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rbwhipple/VRA-FS] Display Flicker (Issue #2)

 

First of all nice job with this project. I just finished putting mine together and am currently testing. The text portions at the top and bottom of the display are flickering with the bottom of the display the worse. I just want to ask if this is expected behavior or do I have a problem? I assume this is just the display being redrawn. Thanks for your time.

**Comment by b-forsberg** [comment]
Thanks for the reply. OK looks my device is now working. I have modified the code to update the header only when data changes. I will looked at the footer another time but its data is changing most of the time.
